apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: apicurio-tenant-manager-fwht
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apicurio-tenant-manager-fwht
    app.kubernetes.io/part-of: apicurio-tenant-manager
  name: apicurio-tenant-manager-fwht
  namespace: nipatil-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: apicurio-tenant-manager-fwht
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: apicurio-tenant-manager-fwht
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:0c56f543a57c1b187a91ca42810f20d6e376e00b955638dcaf3711e8983e750c
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
